version: "3.8"

services:
  db:
    image: postgres:15.1
    container_name: USER_DB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jwt_security
